# Generated by Django 5.0.6 on 2024-06-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('first_prompt', models.CharField(max_length=300)),
                ('second_prompt', models.CharField(max_length=300)),
                ('third_prompt', models.CharField(max_length=300)),
            ],
        ),
    ]
