# Generated by Django 5.0.6 on 2024-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_day_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='day_note',
            field=models.CharField(max_length=250),
        ),
    ]
